### ISSUE TITLE
Peer to peer review from team-78-thehummin

### ISSUE THREAD

**Issue by elmejdki** [dannisonarias/Dannison_Oscar_Embedding_Images_and_Video#1]
teammates FeedBack:
  - Add description to the alt attribute to image elements,
  - Add some <li> and <ul> for the border,
  - More comments on the main page,
  - Good readme file, nice to add with which techno you used to organise your page ( grid system or flexbox ).
  - Use the grid in the comment section cause it is easier,
  - Clean the code in the css file cause there is some empty,
  - It will be better if you minimize the length of the lines in your HTML code to 80 characters long,
  - Nice and will structured HTML and CSS file,
  - Try to remove the comments of code that you do not need any more.

**Comment by dannisonarias** [comment]
Thank you team 78 , your suggestions has been considered and updated .
